services:
  frontend:
    image: workwork-frontend
    ports:
      - 3000:3000
    user: root
    restart: always
    build:
      context: frontend/
  frontend:
    image: workwork-backend
    ports:
      - 4000:5000
    user: root
    restart: always
    build:
      context: backend/
    environment:
      - cookie_expire=grafana.barnowl.de:443
      - domain=http://193.196.38.197:3000/

    