services:
  frontend:
    image: themrphantom/workwork-frontend
    ports:
      - 3000:80
    user: root
    restart: always
    build:
      context: frontend/
  backend:
    image: themrphantom/workwork-backend
    ports:
      - 4000:5000
    user: root
    restart: always
    build:
      context: backend/
    environment:
      - cookie_expire=<time>
      - domain=<domain>
      - adminpw=<pw>
      - db_name=database/data.db
      - standard_sport_name=Allgemein
    volumes:
      - ./docker-volume:/usr/src/app/database

    