services:
  frontend:
    image: themrphantom/workwork-frontend
    ports:
      - 3000:80
    user: root
    restart: always

  backend:
    image: themrphantom/workwork-backend
    ports:
      - 4000:5000
    user: root
    restart: always
    environment:
      - cookie_expire=<time>
      - domain=<domain>
      - adminpw=<pw>
      - db_name=database/data.db
      - standard_sport_name=Allgemein
      - smtp_server=<smtp_server>
      - mail_username=<mail_username>
      - mail_password=<mail_password>
      - server_mail=<server_mail>
    volumes:
      - ./docker-volume:/usr/src/app/database

    